#!/bin/bash
cd /home/chris/cs-check
size=$(( RANDOM % 15 + 30 ))
line="╭"$(printf    "%.0s-" $(seq 1 $((size + 4))))"╮"
bottom="╰---.  "$(printf    "%.0s-" $(seq 1 $((size - 2))))"╯"
cat << ENDL
MIME-Version: 1.0
Content-Type: multipart/alternative; 
 boundary="who-cares/nomatter"
From: Ding Dong <chris@9ol.es>
Subject: Crash Space is Open Y'all!!

This is a MIME-encapsulated message
--who-cares/nomatter
Content-Type: text/html

<html><body>
$(./check-for-events.py)
<center><div style=display:inline-block;text-align:left>
<pre style=font-family:monospace;line-height:1em;white-space:pre>$line
$( (echo "";/usr/games/fortune /home/chris/cs-check/fortunes;echo "") | ./repage.py $size )
$bottom
     \ :
$(/usr/games/fortune characters | gawk ' { if (FNR == 1) { print "  "  substr($0, 0, 4 )   "\\:"  substr($0, 7); } else { print "  "$0  } } ';)
</pre></div></center></body></html>
--who-cares/nomatter--

ENDL
