#!/bin/bash
size=$(( RANDOM % 15 + 30 ))
line="╭"$(printf    "%.0s-" $(seq 1 $((size + 4))))"╮"
bottom="╰---.  "$(printf    "%.0s-" $(seq 1 $((size - 2))))"╯"
cat << ENDL
$line
$( (echo "";fortune fortunes;echo "") | ./repage.py $size no )
$bottom
     \ :
$(fortune characters | gawk ' { if (FNR == 1) { print "  "  substr($0, 0, 4 )   "\\:"  substr($0, 7); } else { print "  "$0  } } ';)
ENDL
